# This is a basic workflow to help you get started with Actions

name: dataaaa

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '12 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Digital Terrestrial Television (DTT) Coverage Database (English)
        # You may pin to the exact commit or the version.
        # uses: githubocto/flat@14d538577eca49658f129ede3cb3ec8cdd6d1bed
        uses: githubocto/flat@v2.0.2
        with:
          # The filename to use for writing data.
          downloaded_filename: dtt_coverage_en.csv
          # A URL containing data to fetch.
          http_url: https://www.ofca.gov.hk/filemanager/ofca/common/datagovhk/dtt_coverage_en.csv
      - name: List of Carrier Licensees (English)
        # You may pin to the exact commit or the version.
        # uses: githubocto/flat@14d538577eca49658f129ede3cb3ec8cdd6d1bed
        uses: githubocto/flat@v2.0.2
        with:
          # The filename to use for writing data.
          downloaded_filename: carrier_lic_en.csv
          # A URL containing data to fetch.
          http_url: https://www.ofca.gov.hk/filemanager/ofca/common/datagovhk/carrier_lic_en.csv
      - name: List of Internet Service Providers (ISP) (English)
        # You may pin to the exact commit or the version.
        # uses: githubocto/flat@14d538577eca49658f129ede3cb3ec8cdd6d1bed
        uses: githubocto/flat@v2.0.2
        with:
          # The filename to use for writing data.
          downloaded_filename: isp_en.csv
          # A URL containing data to fetch.
          http_url: https://www.ofca.gov.hk/filemanager/ofca/common/datagovhk/isp_en.csv
      - name: Names of Broadcasting Licensees and their Registered Addresses (English)
        # You may pin to the exact commit or the version.
        # uses: githubocto/flat@14d538577eca49658f129ede3cb3ec8cdd6d1bed
        uses: githubocto/flat@v2.0.2
        with:
          # The filename to use for writing data.
          downloaded_filename: Broadcasting_Licensee_List_en.csv
          # A URL containing data to fetch.
          http_url: https://www.ofca.gov.hk/filemanager/ofca/common/datagovhk/Broadcasting_Licensee_List_en.csv
      - name: Register of Public Payphone
        # You may pin to the exact commit or the version.
        # uses: githubocto/flat@14d538577eca49658f129ede3cb3ec8cdd6d1bed
        uses: githubocto/flat@v2.0.2
        with:
          # The filename to use for writing data.
          downloaded_filename: PayPhoneRegister.csv
          # A URL containing data to fetch.
          http_url: https://www.ofca.gov.hk/filemanager/ofca/common/datagovhk/PayPhoneRegister.csv
